version: "3.9"
services:
  rabbitMQServer:
    container_name: rabbitMQ
    image: rabbitmq:3.10-management
    restart: always
    networks:
        - parkingAds_net
    ports:
        - 5672:5672 
        - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
    depends_on:
      - seq
    volumes:
      - ./rabbitmq:/data

  seq:
    # SeQ is a framework for logging of exceptions etc
    container_name: ParkingAds.SeQ
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
    networks:
        - parkingAds_net
    volumes:
      - ./seq-data:/data

  # smtp4dev:
  #   # development time email server and client, easy to test sending emails
  #   container_name: ParkingAds.Smtp4dev
  #   image: rnwood/smtp4dev:latest
  #   ports:
  #     - 8082:80
  #     - 26:25
  #   networks:
  #       - parkingAds_net

  parkingservice:
    container_name: ParkingAds.ParkingService
    image: kidskids5817/psuparkingservice
    restart: unless-stopped
    ports:
      - 8083:80
    networks:
        - parkingAds_net

  adservice:
    container_name: ParkingAds.AdService
    image: kidskids5817/psuadservice
    restart: unless-stopped
    ports:
      - 8084:80
    networks:
        - parkingAds_net

  proxy:
    container_name: proxy
    image: kidskids5817/adproxy:arm
    ports:
      - 83:80
    depends_on: 
      - adservice
    networks:
        - parkingAds_net

  console:
    container_name: ParkingAds.console
    image: kidskids5817/parkingads-console:arm
    depends_on: 
      - rabbitMQServer
      - proxy
    networks:
        - parkingAds_net
    environment:
      RABBITMQ_HOST: "rabbitMQ"

  parking:
    container_name: parking
    image: kidskids5817/parkingservice:arm
    depends_on: 
      - rabbitMQServer
    networks:
        - parkingAds_net
    environment:
      RABBITMQ_HOST: "rabbitMQ"

  hotel:
    container_name: hotel
    image: kidskids5817/hotelservice:arm
    depends_on: 
      - rabbitMQServer
    networks:
        - parkingAds_net
    environment:
      RABBITMQ_HOST: "rabbitMQ"
      AMADEUS_CLINET_ID: "IGhg5sxWUxzQlck2GqHWkRgbc7aGA4RM"
      AMADEUS_CLIENT_SECRET: "h4BFfroouLoPFac3"

  ad:
    container_name: ad
    image: kidskids5817/adservice:arm
    depends_on: 
      - rabbitMQServer
    networks:
        - parkingAds_net
    environment:
      RABBITMQ_HOST: "rabbitMQ"
      SEQ: "http://seq:80"
      SEQ_API_KEY: "14X7q4Dngg8sBbKa72ZK"
      ADSERVICE: "http://proxy:80"
networks:
    parkingAds_net:



