apiVersion: v1
kind: Service
metadata:
 name: ad-svc
spec:
 selector:
   role: app
 ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
     nodePort: 32001
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ad-deployment
 labels:
   role: app
spec:
 replicas: 2
 selector:
   matchLabels:
     role: app
 template:
   metadata:
     labels:
       role: app
   spec:
     containers:
     - name: app
       image: "kidskids5817/psuadservice"
     - name: web
       image: "kidskids5817/web"