# the adservice receving request from rabbitmq
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  labels:
    app: ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad
  template:
    metadata:
      labels:
        app: ad
    spec:
      containers:
        - name: ad
          image: kidskids5817/adservice:test2
          env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: rabbitmq-host
          - name: SEQ
            valueFrom:
              configMapKeyRef:
                name: seq-configmap
                key: seq
          - name: SEQ_API_KEY
            valueFrom:
              secretKeyRef:
                name: seq-secret
                key: seq-api-key
          - name: ADSERVICE
            valueFrom:
              configMapKeyRef:
                name: adservice-configmap
                key: ad-svc
---
apiVersion: v1
kind: Service
metadata:
  name: ad-service
spec:
  selector:
    app: ad
  ports:
    - protocol: TCP
      port: 80