apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingads-web
  labels:
    app: parkingads-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingads-web
  template:
    metadata:
      labels:
        app: parkingads-web
    spec:
      containers:
        - name: parkingads-web
          image: kidskids5817/parkingads-web
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: parkingads-web-service
spec:
  selector:
    app: parkingads-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80