apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingads-console
  labels:
    app: parkingads-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingads-console
  template:
    metadata:
      labels:
        app: parkingads-console
    spec:
      containers:
        - name: parkingads-console
          image: kidskids5817/ui
          env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: rabbitmq-host
          - name: ADSERVICE
            valueFrom:
              configMapKeyRef:
                name: adservice-configmap
                key: ad-svc
