apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking
  labels:
    app: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking
  template:
    metadata:
      labels:
        app: parking
    spec:
      containers:
        - name: parking
          image: kidskids5817/parkingservice:amd
          env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: rabbitmq-host
---
apiVersion: v1
kind: Service
metadata:
  name: parking-service
spec:
  selector:
    app: parking
  ports:
    - protocol: TCP
      port: 80