apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingads-console
  labels:
    app: parkingads-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingads-console
  template:
    metadata:
      labels:
        app: parkingads-console
    spec:
      containers:
        - name: parkingads-console
          image: kidskids5817/parkingads-console:arm
          env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: rabbitmq-host
---
apiVersion: v1
kind: Service
metadata:
  name: parkingads-console-service
spec:
  selector:
    app: parkingads-console
  ports:
    - protocol: TCP
      port: 80