apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  labels:
    app: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
          - containerPort: 80
          env:
          - name: ACCEPT_EULA
            value: 'Y'
---
apiVersion: v1
kind: Service
metadata:
  name: seq-service
spec:
  selector:
    app: seq
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 80
      nodePort: 32000