apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitMQ
  labels:
    app: rabbitMQ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitMQ
  template:
    metadata:
      labels:
        app: rabbitMQ
    spec:
      containers:
        - name: rabbitMQ
          image: rabbitmq:3.10-management
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitMQ-service
spec:
  selector:
    app: rabbitMQ
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000